import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { Bell, BriefcaseBusiness, ExternalLink, FileText, LayoutDashboard, LogOut, Menu, MessageSquare, Package, Pencil, Plus, Reply, ShoppingCart, Trash2, X } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { api, auth } from '../api'

const navigation=[[LayoutDashboard,'Overview'],[BriefcaseBusiness,'Services'],[FileText,'Projects'],[Package,'Products'],[ShoppingCart,'Orders'],[MessageSquare,'Messages']]

export default function Dashboard(){
  const [side,setSide]=useState(false)
  const [section,setSection]=useState('Overview')
  const [data,setData]=useState(null)
  const [error,setError]=useState('')
  const [editor,setEditor]=useState(null)
  const [notificationsOpen,setNotificationsOpen]=useState(false)
  const [accountOpen,setAccountOpen]=useState(false)
  const navigate=useNavigate()

  async function load(){
    try{
      await api('/auth/me')
      const [dashboard,services,projects,products,orders,messages]=await Promise.all([api('/dashboard'),api('/services'),api('/projects'),api('/products'),api('/orders'),api('/messages')])
      setData({dashboard,services,projects,products,orders,messages});setError('')
    }catch(err){if(err.message==='Unauthorized'){auth.clear();navigate('/admin/login')}else setError(err.message)}
  }
  useEffect(()=>{load()},[])
  async function update(collection,id,changes){try{await api(`/${collection}/${id}`,{method:'PATCH',body:JSON.stringify(changes)});await load()}catch(err){setError(err.message)}}
  async function remove(collection,id){if(!confirm('Delete this item permanently?'))return;try{await api(`/${collection}/${id}`,{method:'DELETE'});await load()}catch(err){setError(err.message)}}
  async function save(collection,values,id){try{await api(`/${collection}${id?`/${id}`:''}`,{method:id?'PATCH':'POST',body:JSON.stringify(values)});setEditor(null);await load()}catch(err){throw err}}
  async function markAllRead(){const unread=data.messages.filter(message=>!message.read);await Promise.all(unread.map(message=>api(`/messages/${message.id}`,{method:'PATCH',body:JSON.stringify({read:true})})));await load()}
  function signOut(){auth.clear();navigate('/admin/login')}

  return <main className="min-h-screen bg-[#f4f7f9] text-[#132b40]">
    <aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-[#071f33] p-5 text-white transition-transform lg:translate-x-0 ${side?'translate-x-0':'-translate-x-full'}`}>
      <div className="flex items-center justify-between"><Link to="/" className="text-xl font-extrabold">4CC <span className="text-[#e97824]">INC.</span></Link><button className="lg:hidden" onClick={()=>setSide(false)}><X/></button></div>
      <Link to="/" target="_blank" className="mt-7 flex items-center justify-center gap-2 rounded-lg border border-white/15 px-4 py-3 text-sm font-bold text-white hover:bg-white/10"><ExternalLink size={17}/> Visit website</Link>
      <p className="mt-7 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Manage website</p>
      <nav className="mt-3 space-y-1">{navigation.map(([Icon,label])=><button onClick={()=>{setSection(label);setSide(false)}} key={label} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold ${section===label?'bg-[#e97824] text-white':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon size={18}/>{label}{label==='Messages'&&data?.dashboard.counts.unread>0&&<span className="ml-auto rounded-full bg-white px-2 py-0.5 text-[10px] text-[#e97824]">{data.dashboard.counts.unread}</span>}{label==='Orders'&&data?.dashboard.counts.newOrders>0&&<span className="ml-auto rounded-full bg-white px-2 py-0.5 text-[10px] text-[#e97824]">{data.dashboard.counts.newOrders}</span>}</button>)}</nav>
    </aside>
    <section className="lg:pl-64">
      <header className="relative flex h-[74px] items-center justify-between border-b border-slate-200 bg-white px-5 md:px-8"><div className="flex items-center gap-3"><button onClick={()=>setSide(true)} className="lg:hidden"><Menu/></button><div><h1 className="text-lg font-bold">{section}</h1><p className="hidden text-xs text-slate-400 sm:block">Welcome back, Administrator</p></div></div><div className="flex items-center gap-3"><Link to="/" target="_blank" className="hidden items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold hover:border-[#e97824] hover:text-[#e97824] sm:flex"><ExternalLink size={15}/> Visit website</Link><div className="relative"><button onClick={()=>{setNotificationsOpen(!notificationsOpen);setAccountOpen(false)}} aria-label="Notifications" className="relative grid h-10 w-10 place-items-center rounded-full bg-slate-100 text-slate-500 hover:bg-orange-50 hover:text-[#e97824]"><Bell size={18}/>{data?.dashboard.counts.unread>0&&<span className="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full bg-[#e97824] px-1 text-[10px] font-bold text-white">{data.dashboard.counts.unread}</span>}</button>{notificationsOpen&&<NotificationMenu messages={data?.messages||[]} markAll={markAllRead} openMessages={()=>{setSection('Messages');setNotificationsOpen(false)}}/>}</div><div className="relative"><button onClick={()=>{setAccountOpen(!accountOpen);setNotificationsOpen(false)}} aria-label="Admin account menu" className="grid h-10 w-10 place-items-center rounded-full bg-[#0b2940] text-xs font-bold text-white ring-2 ring-transparent hover:ring-orange-200">AD</button>{accountOpen&&<div className="absolute right-0 top-12 z-50 w-56 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl"><div className="border-b border-slate-100 p-4"><p className="text-sm font-bold">Administrator</p><p className="mt-0.5 text-xs text-slate-400">admin@4ccinc.so</p></div><Link to="/" target="_blank" className="flex items-center gap-3 px-4 py-3 text-sm font-semibold hover:bg-slate-50"><ExternalLink size={16}/> Visit website</Link><button onClick={signOut} className="flex w-full items-center gap-3 border-t border-slate-100 px-4 py-3 text-sm font-semibold text-red-600 hover:bg-red-50"><LogOut size={16}/> Sign out</button></div>}</div></div></header>
      <div className="p-5 md:p-8">{error?<p className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p>:!data?<p className="text-slate-500">Loading dashboard…</p>:section==='Overview'?<Overview data={data} setSection={setSection}/>:section==='Messages'?<Messages items={data.messages} update={update} remove={remove}/>:section==='Orders'?<Orders items={data.orders} update={update} remove={remove}/>:<Records section={section} items={section==='Services'?data.services:section==='Projects'?data.projects:data.products} update={update} remove={remove} edit={setEditor}/>}</div>
    </section>
    {editor&&<Editor section={section} item={editor===true?null:editor} close={()=>setEditor(null)} save={save}/>} 
  </main>
}

function NotificationMenu({messages,markAll,openMessages}){
  const unread=messages.filter(message=>!message.read)
  return <div className="absolute right-0 top-12 z-50 w-[min(22rem,calc(100vw-2rem))] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">
    <div className="flex items-center justify-between border-b border-slate-100 p-4"><div><p className="text-sm font-bold">Notifications</p><p className="text-xs text-slate-400">{unread.length?`${unread.length} unread enquiries`:'You’re all caught up'}</p></div>{unread.length>0&&<button onClick={markAll} className="text-xs font-bold text-[#e97824]">Mark all read</button>}</div>
    <div className="max-h-96 divide-y divide-slate-100 overflow-y-auto">{messages.length?messages.slice(0,5).map(message=><article key={message.id} className={`flex gap-3 p-4 ${message.read?'bg-white':'bg-orange-50/40'}`}><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${message.read?'bg-slate-300':'bg-[#e97824]'}`}/><div className="min-w-0 flex-1"><p className="text-sm font-bold">{message.name}</p><a href={`mailto:${message.email}`} className="text-[11px] text-slate-400 hover:text-[#e97824]">{message.email}</a><p className="mt-2 whitespace-pre-wrap break-words text-xs leading-5 text-slate-600">{message.message}</p><div className="mt-3 flex items-center justify-between gap-3"><p className="text-[10px] text-slate-400">{new Date(message.createdAt).toLocaleString()}</p><ReplyLink message={message} compact/></div></div></article>):<div className="p-7 text-center"><Bell className="mx-auto text-slate-300"/><p className="mt-2 text-sm text-slate-500">No messages yet</p></div>}</div>
    <button onClick={openMessages} className="w-full border-t border-slate-100 p-3 text-center text-xs font-bold text-[#e97824] hover:bg-orange-50">View all messages</button>
  </div>
}

function Overview({data,setSection}){const c=data.dashboard.counts;return <><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-extrabold">Dashboard overview</h2><p className="mt-1 text-sm text-slate-500">Live content and enquiries from your website.</p></div><Link to="/" target="_blank" className="flex items-center gap-2 rounded-lg bg-[#0b2940] px-5 py-3 text-sm font-bold text-white hover:bg-[#e97824]"><ExternalLink size={16}/> Open public website</Link></div><div className="mt-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{[[BriefcaseBusiness,'Active services',c.services],[FileText,'Published projects',c.projects],[MessageSquare,'Unread messages',c.unread],[Bell,'All enquiries',c.messages]].map(([Icon,label,n])=><article key={label} className="rounded-xl border border-slate-200 bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-lg bg-orange-50 text-[#e97824]"><Icon size={19}/></span><p className="mt-5 text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-extrabold">{n}</p></article>)}</div><article className="mt-6 rounded-xl border border-slate-200 bg-white p-6"><div className="flex justify-between"><h3 className="font-bold">Recent enquiries</h3><button onClick={()=>setSection('Messages')} className="text-xs font-bold text-[#e97824]">View all</button></div><div className="mt-4 divide-y divide-slate-100">{data.dashboard.recentMessages.length?data.dashboard.recentMessages.map(m=><div key={m.id} className="py-4"><p className="text-sm font-bold">{m.name} <span className="font-normal text-slate-400">— {m.email}</span></p><p className="mt-1 truncate text-sm text-slate-500">{m.message}</p></div>):<p className="py-5 text-sm text-slate-400">No enquiries yet.</p>}</div></article></>}

function Records({section,items,update,remove,edit}){const collection=section.toLowerCase();return <><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-extrabold">Manage {collection}</h2><p className="mt-1 text-sm text-slate-500">Published changes appear on the public website.</p></div><button onClick={()=>edit(true)} className="flex items-center gap-2 rounded-lg bg-[#e97824] px-5 py-3 text-sm font-bold text-white"><Plus size={17}/> Add {section.slice(0,-1).toLowerCase()}</button></div><div className="mt-7 divide-y divide-slate-100 overflow-hidden rounded-xl border border-slate-200 bg-white">{items.map(item=><div key={item.id} className="flex items-center gap-4 p-4">{item.image&&<img src={item.image} alt="" className="h-12 w-12 rounded-lg object-cover"/>}<div className="min-w-0"><p className="font-bold">{item.title}</p><p className="truncate text-xs text-slate-400">{item.text||item.description||`${item.category} · ${item.location}`}</p>{section==='Products'&&<p className="mt-1 text-xs font-bold text-[#e97824]">{item.company} · {item.currency} {item.price}/{item.unit}</p>}</div><button onClick={()=>update(collection,item.id,{active:!item.active})} className={`ml-auto rounded-full px-3 py-1 text-[10px] font-bold ${item.active?'bg-green-50 text-green-700':'bg-slate-100 text-slate-500'}`}>{item.active?'Published':'Hidden'}</button><button onClick={()=>edit(item)} title="Edit" className="text-slate-400 hover:text-[#e97824]"><Pencil size={17}/></button><button onClick={()=>remove(collection,item.id)} title="Delete" className="text-slate-400 hover:text-red-600"><Trash2 size={17}/></button></div>)}</div></>}

function Orders({items,update,remove}){return <><div><h2 className="text-2xl font-extrabold">Product orders</h2><p className="mt-1 text-sm text-slate-500">Contact customers, then update each order’s progress.</p></div><div className="mt-7 space-y-4">{items.length?items.map(order=><article key={order.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#e97824]">{order.company}</p><h3 className="mt-1 text-lg font-bold">{order.quantity} × {order.productTitle}</h3><p className="mt-1 text-sm font-bold text-slate-500">Estimated: {order.currency} {(order.unitPrice*order.quantity).toLocaleString()}</p></div><select value={order.status} onChange={e=>update('orders',order.id,{status:e.target.value})} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold outline-none"><option value="new">New</option><option value="contacted">Contacted</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-2"><p><b>Customer:</b> {order.name}</p><p><b>Phone:</b> <a className="text-[#e97824]" href={`tel:${order.phone}`}>{order.phone}</a></p>{order.email&&<p><b>Email:</b> <a className="text-[#e97824]" href={`mailto:${order.email}`}>{order.email}</a></p>}<p><b>Location:</b> {order.address}</p>{order.notes&&<p className="sm:col-span-2"><b>Notes:</b> {order.notes}</p>}</div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><p className="text-xs text-slate-400">{new Date(order.createdAt).toLocaleString()}</p><div className="flex gap-2"><a href={`https://wa.me/${order.phone.replace(/\D/g,'')}?text=${encodeURIComponent(`Hello ${order.name}, regarding your order for ${order.quantity} × ${order.productTitle} from 4CC INC.`)}`} target="_blank" rel="noreferrer" className="rounded-lg bg-green-600 px-3 py-2 text-xs font-bold text-white">WhatsApp</a><button onClick={()=>remove('orders',order.id)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={17}/></button></div></div></article>):<p className="rounded-xl border border-slate-200 bg-white p-10 text-center text-slate-400">No product orders yet.</p>}</div></>}

function Messages({items,update,remove}){return <><h2 className="text-2xl font-extrabold">Customer enquiries</h2><p className="mt-1 text-sm text-slate-500">Read enquiries and reply directly to the sender.</p><div className="mt-7 divide-y divide-slate-100 overflow-hidden rounded-xl border border-slate-200 bg-white">{items.length?items.map(m=><div key={m.id} className="flex items-start gap-4 p-4"><button onClick={()=>update('messages',m.id,{read:!m.read})} className={`mt-1 h-3 w-3 shrink-0 rounded-full ${m.read?'bg-slate-300':'bg-[#e97824]'}`} title="Toggle read"/><div className="min-w-0 flex-1"><p className="font-bold">{m.name} <a href={`mailto:${m.email}`} className="text-xs font-normal text-[#e97824]">{m.email}</a></p><p className="text-xs text-slate-400">{m.service||'General enquiry'} · {new Date(m.createdAt).toLocaleString()}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{m.message}</p><div className="mt-4"><ReplyLink message={m}/></div></div><button onClick={()=>remove('messages',m.id)} title="Delete message" className="text-slate-400 hover:text-red-600"><Trash2 size={17}/></button></div>):<p className="p-8 text-center text-slate-400">No enquiries yet.</p>}</div></>}

function ReplyLink({message,compact=false}){const [open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api(`/messages/${message.id}/reply`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setSent(true)}catch(err){setError(err.message)}finally{setBusy(false)}}return <><button onClick={()=>setOpen(true)} className={`inline-flex items-center gap-2 rounded-lg bg-[#0b2940] font-bold text-white hover:bg-[#e97824] ${compact?'px-3 py-1.5 text-[10px]':'px-4 py-2 text-xs'}`}><Reply size={compact?12:15}/> Reply</button>{open&&createPortal(<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4">{sent?<div className="w-full max-w-lg rounded-2xl bg-white p-8 text-center shadow-2xl"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-green-50 text-green-600"><Reply/></span><h2 className="mt-4 text-2xl font-extrabold">Reply sent</h2><p className="mt-2 text-sm text-slate-500">Your response was emailed to {message.email}.</p><button onClick={()=>setOpen(false)} className="mt-6 rounded-lg bg-[#0b2940] px-5 py-3 text-sm font-bold text-white">Done</button></div>:<form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#e97824]">Reply to enquiry</p><h2 className="mt-1 text-xl font-extrabold">{message.name}</h2><p className="text-xs text-slate-400">{message.email}</p></div><button type="button" onClick={()=>setOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X/></button></div><div className="mt-6 space-y-4"><Field name="subject" label="Subject" value={`Re: ${message.service||'Your enquiry to 4CC INC.'}`} required/><Field name="message" label="Your reply" value={`Hello ${message.name},\n\nThank you for contacting 4CC INC.\n\n\n\nBest regards,\n4CC INC.`} textarea required/></div>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border border-slate-200 px-5 py-3 text-sm font-bold">Cancel</button><button disabled={busy} className="flex items-center gap-2 rounded-lg bg-[#e97824] px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Reply size={15}/>{busy?'Sending…':'Send reply'}</button></div></form>}</div>,document.body)}</>}

function Editor({section,item,close,save}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);const project=section==='Projects',product=section==='Products';async function submit(e){e.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));values.active=item?.active!==false;values.featured=values.featured==='on';try{await save(section.toLowerCase(),values,item?.id)}catch(err){setError(err.message);setBusy(false)}}return <div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={submit} className="my-6 w-full max-w-xl rounded-2xl bg-white p-7 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#e97824]">{item?'Edit':'New'} content</p><h2 className="mt-1 text-2xl font-extrabold">{item?item.title:`Add ${section.slice(0,-1).toLowerCase()}`}</h2></div><button type="button" onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X/></button></div><div className="mt-6 space-y-4"><Field name="title" label="Title" value={item?.title} required/>{project?<><Field name="category" label="Category" value={item?.category} required/><Field name="location" label="Location" value={item?.location} required/><Field name="image" label="Image URL" value={item?.image} type="url" required/></>:product?<><Field name="company" label="Partner company" value={item?.company} required/><Field name="category" label="Category" value={item?.category} required/><div className="grid grid-cols-3 gap-3"><Field name="price" label="Price" value={item?.price} type="number" min="0" step="0.01" required/><Field name="currency" label="Currency" value={item?.currency||'USD'} required/><Field name="unit" label="Unit" value={item?.unit} placeholder="item / carton" required/></div><Field name="image" label="Image URL" value={item?.image} type="url" required/><Field name="description" label="Description" value={item?.description} textarea required/><label className="flex items-center gap-2 text-sm font-bold"><input name="featured" type="checkbox" defaultChecked={item?.featured}/> Feature this product</label></>:<><Field name="number" label="Display number" value={item?.number}/><Field name="text" label="Description" value={item?.text} textarea required/></>}</div>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-7 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-lg border border-slate-200 px-5 py-3 text-sm font-bold">Cancel</button><button disabled={busy} className="rounded-lg bg-[#e97824] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?'Saving…':'Save and publish'}</button></div></form></div>}
function Field({label,textarea,...props}){const Tag=textarea?'textarea':'input';return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><Tag {...props} defaultValue={props.value||''} value={undefined} rows={textarea?4:undefined} className="w-full rounded-lg border border-slate-200 px-4 py-3 text-sm outline-none focus:border-[#e97824]"/></label>}
