import { ArrowRight, CheckCircle2, MoveRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CTA } from '../components'
import { projects, services } from '../data'

export default function Home() {
  const warehouseHero = `${import.meta.env.BASE_URL}images/warehouse-hero.png`
  return <>
    <section className="hero-bg relative min-h-[720px] overflow-hidden text-white" style={{ '--hero-image': `url(${warehouseHero})` }}><div className="grid-pattern absolute inset-0 opacity-40"/><div className="container-page relative flex min-h-[720px] items-center py-24"><div className="max-w-[700px] reveal"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-[11px] font-bold uppercase tracking-[.18em] backdrop-blur"><span className="h-2 w-2 rounded-full bg-[#e97824]"/>Quality. Control. Confidence.</span><h1 className="mt-7 text-5xl font-extrabold leading-[1.06] tracking-[-.04em] sm:text-6xl lg:text-[76px]">Precision behind<br/><span className="text-[#f28a36]">every movement.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-200 sm:text-lg">Independent inspection and logistics expertise that protects your products, strengthens your supply chain and keeps business moving.</p><div className="mt-9 flex flex-wrap gap-4"><Link to="/services" className="flex items-center gap-2 rounded-lg bg-[#e97824] px-6 py-4 text-sm font-bold transition hover:bg-[#cf6417]">Explore our services <ArrowRight size={17}/></Link><Link to="/contact" className="rounded-lg border border-white/40 px-6 py-4 text-sm font-bold transition hover:bg-white hover:text-[#0b2940]">Speak with an expert</Link></div></div></div><div className="absolute bottom-0 right-0 hidden border-l border-white/10 bg-[#071f33]/85 px-9 py-6 backdrop-blur md:block"><p className="text-[11px] uppercase tracking-widest text-slate-400">Based in</p><p className="mt-1 font-display font-bold">Mogadishu, Somalia</p></div></section>

    <section className="border-b border-slate-200 bg-white"><div className="container-page grid grid-cols-2 divide-x divide-slate-200 md:grid-cols-4">{[['10+','Years experience'],['300+','Inspections'],['24/7','Operational support'],['100%','Independent reporting']].map(([n,l])=><div className="px-4 py-8 text-center" key={l}><p className="font-display text-2xl font-extrabold text-[#0b2940] md:text-3xl">{n}</p><p className="mt-1 text-xs font-medium text-slate-500">{l}</p></div>)}</div></section>

    <section className="section-pad bg-[#f8fafb]"><div className="container-page"><div className="grid gap-8 md:grid-cols-[1fr_.8fr] md:items-end"><div><span className="eyebrow">What we do</span><h2 className="mt-4 max-w-2xl text-4xl font-extrabold leading-tight text-[#0b2940] md:text-5xl">Expert oversight at every critical point.</h2></div><p className="max-w-lg leading-7 text-slate-600">From the warehouse floor to final delivery, our local knowledge and disciplined processes give you a clear view of your operation.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{services.map(({icon:Icon,number,title,text})=><article key={title} className="card-lift group rounded-2xl border border-slate-200 bg-white p-7"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-xl bg-orange-50 text-[#e97824]"><Icon size={24}/></span><span className="text-xs font-bold text-slate-300">{number}</span></div><h3 className="mt-7 text-xl font-bold text-[#0b2940]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p><Link to="/services" className="mt-6 flex items-center gap-2 text-sm font-bold text-[#e97824]">Learn more <MoveRight size={16}/></Link></article>)}</div></div></section>

    <section className="section-pad bg-white"><div className="container-page grid items-center gap-16 lg:grid-cols-2"><div className="relative"><img src={warehouseHero} alt="4CC quality inspectors in a warehouse" className="h-[520px] w-full rounded-2xl object-cover object-[70%_center]"/><div className="absolute -bottom-7 -right-3 w-56 rounded-xl bg-[#0b2940] p-6 text-white shadow-2xl md:-right-7"><p className="text-4xl font-extrabold text-[#e97824]">10+</p><p className="mt-2 text-sm leading-6 text-slate-300">Years of local operational expertise</p></div></div><div><span className="eyebrow">Who we are</span><h2 className="mt-4 text-4xl font-extrabold leading-tight text-[#0b2940] md:text-5xl">Local insight.<br/>International standards.</h2><p className="mt-6 leading-8 text-slate-600">4CC INC. is a Mogadishu-based quality control and logistics partner. We combine deep knowledge of the local operating environment with clear, disciplined systems to protect the integrity of every assignment.</p><div className="mt-7 space-y-4">{['Unbiased, evidence-based reporting','Experienced local inspection teams','Responsive support throughout the operation'].map(x=><p key={x} className="flex items-center gap-3 text-sm font-semibold text-[#153047]"><CheckCircle2 className="text-[#e97824]" size={20}/>{x}</p>)}</div><Link to="/about" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#0b2940]">Discover our company <ArrowRight size={17} className="text-[#e97824]"/></Link></div></div></section>

    <section className="section-pad bg-[#071f33] text-white"><div className="container-page"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="eyebrow">Selected work</span><h2 className="mt-4 text-4xl font-extrabold md:text-5xl">Results you can see.</h2></div><Link to="/projects" className="flex items-center gap-2 text-sm font-bold">View all projects <ArrowRight className="text-[#e97824]" size={17}/></Link></div><div className="mt-12 grid gap-6 md:grid-cols-3">{projects.map(p=><article key={p.title} className="group overflow-hidden rounded-2xl bg-white/5"><div className="h-64 overflow-hidden"><img src={p.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#e97824]">{p.category}</p><h3 className="mt-2 text-xl font-bold">{p.title}</h3><p className="mt-2 text-sm text-slate-400">{p.location}</p></div></article>)}</div></div></section><CTA/>
  </>
}
