import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const so = {
  'Home':'Bogga Hore','About Us':'Nagu Saabsan','Leadership':'Hoggaanka','Services':'Adeegyada','Projects':'Mashaariicda','Products':'Badeecooyinka','Contact':'Nala Soo Xiriir','Request a Quote':'Codso Qiimeyn',
  'Our leadership':'Hoggaankeenna','The people guiding 4CC INC.':'Dadka hoggaamiya 4CC INC.','Meet the company leaders responsible for our direction, operational standards and commitment to clients.':'La kulan hoggaamiyeyaasha shirkadda ee mas’uulka ka ah jihadeenna, heerarka hawlgalka iyo u heellanaanta macaamiisha.','Owners & executives':'Milkiilayaasha iyo madaxda','Leadership built on responsibility.':'Hoggaan ku dhisan mas’uuliyad.','Our leadership combines strategic oversight with direct knowledge of Somalia’s operating environment.':'Hoggaankeenna wuxuu isku daraa kormeer istaraatiiji ah iyo aqoon toos ah oo deegaanka shaqo ee Soomaaliya ah.','Chief Executive Officer (CEO)':'Madaxa Fulinta (CEO)','Chief Operating Officer (COO)':'Madaxa Hawlgallada (COO)',
  'Partner marketplace':'Suuqa shirkadaha aan wadaagno','Quality products from trusted companies.':'Badeecooyin tayo leh oo ka socda shirkado lagu kalsoon yahay.','Discover goods offered by our partner businesses and send an order request directly to our sales team.':'Soo hel badeecooyinka ay bixiyaan shirkadaha aan wadaagno, codsiga dalabkana si toos ah ugu dir kooxdayada iibka.','Featured products':'Badeecooyin la soo xulay','Find what your business needs.':'Hel waxa ganacsigaagu u baahan yahay.','Order':'Dalbo','Order request':'Codsiga dalabka','Phone / WhatsApp':'Telefoon / WhatsApp','Quantity':'Tirada','Delivery location':'Goobta gaarsiinta','Additional notes':'Faahfaahin dheeraad ah','Submit order request':'Gudbi codsiga dalabka','Order request received':'Codsiga dalabka waa la helay','Our team will contact you to confirm price, availability and delivery.':'Kooxdayadu way kula soo xiriiri doontaa si loo xaqiijiyo qiimaha, helitaanka iyo gaarsiinta.','Featured':'La soo xulay',
  'Quality. Control. Confidence.':'Tayo. Xakameyn. Kalsooni.','Precision behind':'Saxnaan ka dambaysa','every movement.':'dhaqdhaqaaq kasta.','Independent inspection and logistics expertise that protects your products, strengthens your supply chain and keeps business moving.':'Kormeer madax-bannaan iyo khibrad saadka ah oo ilaalisa badeecadahaaga, xoojisa silsiladda sahayda, ganacsigana dhaqaajisa.','Explore our services':'Eeg adeegyadayada','Speak with an expert':'La hadal khabiir','Based in':'Xaruntu waa','Mogadishu, Somalia':'Muqdisho, Soomaaliya',
  'Years experience':'Sano oo waayo-aragnimo ah','Inspections':'Kormeerro','Operational support':'Taageero hawlgal','Independent reporting':'Warbixin madax-bannaan','What we do':'Waxa aan qabanno','Expert oversight at every critical point.':'Kormeer khabiirnimo meel kasta oo muhiim ah.','From the warehouse floor to final delivery, our local knowledge and disciplined processes give you a clear view of your operation.':'Laga bilaabo bakhaarka ilaa gaarsiinta ugu dambaysa, aqoonteenna deegaanka iyo habraacyadeenna nidaamsan waxay kuu caddeeyaan hawlgalkaaga.','Learn more':'Wax badan ogow',
  'Who we are':'Cidda aan nahay','Local insight.':'Aqoon maxalli ah.','International standards.':'Heerarka caalamiga ah.','Years of local operational expertise':'Sano oo khibrad hawlgal maxalli ah','4CC INC. is a Mogadishu-based quality control and logistics partner. We combine deep knowledge of the local operating environment with clear, disciplined systems to protect the integrity of every assignment.':'4CC INC. waa shirkad fadhigeedu yahay Muqdisho oo ku takhasustay xakamaynta tayada iyo saadka. Waxaan isku darnaa aqoon qoto dheer oo deegaanka ah iyo nidaamyo hufan si aan u ilaalino hawl kasta.','Unbiased, evidence-based reporting':'Warbixin caddayn ku dhisan oo aan eex lahayn','Experienced local inspection teams':'Kooxo kormeer oo maxalli ah oo khibrad leh','Responsive support throughout the operation':'Taageero degdeg ah inta hawlgalku socdo','Discover our company':'Baro shirkaddeenna',
  'Selected work':'Shaqooyin la xushay','Results you can see.':'Natiijooyin aad arki karto.','View all projects':'Eeg dhammaan mashaariicda','Let’s work together':'Aan wada shaqayno','Need dependable oversight for your next operation?':'Ma u baahan tahay kormeer lagu kalsoonaan karo hawlgalkaaga xiga?','Talk to our team':'La hadal kooxdayada',
  'Quality Control':'Xakamaynta Tayada','Warehouse Inspection':'Kormeerka Bakhaarka','Supply Chain Logistics':'Saadka Silsiladda Sahayda','Compliance Assurance':'Hubinta U Hoggaansanaanta','Distribution Logistics':'Saadka Qaybinta',
  'Independent quality verification at every critical point, helping you protect product standards and reduce operational risk.':'Hubin tayo oo madax-bannaan meel kasta oo muhiim ah, taas oo kaa caawinaysa ilaalinta heerarka badeecadda iyo yaraynta khatarta hawlgalka.','Thorough facility, inventory and handling assessments built around accuracy, safety and clear reporting.':'Qiimayn dhammaystiran oo xarunta, kaydka iyo maaraynta ah, kuna dhisan saxnaan, badbaado iyo warbixin cad.','Reliable coordination and oversight that keeps goods moving smoothly from origin through final delivery.':'Isku-duwid iyo kormeer lagu kalsoonaan karo oo badeecadaha si habsami leh uga dhaqaajiya halka ay ka yimaadeen ilaa gaarsiinta ugu dambaysa.','Practical checks and documentation that align your operations with required standards and specifications.':'Kormeer iyo dukumenti wax-ku-ool ah oo hawlgalladaada waafajinaya heerarka iyo shuruudaha loo baahan yahay.',
  'About 4CC':'Ku saabsan 4CC','Built on integrity. Driven by precision.':'Daacadnimo lagu dhisay. Saxnaan lagu hoggaamiyo.','We help organizations operate with confidence through independent oversight and reliable logistics support.':'Waxaan ururrada ka caawinnaa inay si kalsooni leh u shaqeeyaan anagoo siinayna kormeer madax-bannaan iyo taageero saadka lagu kalsoonaan karo.','Our company':'Shirkaddeenna','A trusted partner on the ground.':'Saaxiib lagu kalsoonaan karo oo goobta jooga.','Independent judgment':'Go’aan madax-bannaan','Clear documentation':'Dukumenti cad','Local expertise':'Khibrad maxalli ah','Responsive delivery':'Fulinta degdegga ah','Our Mission':'Himiladeenna','Our Vision':'Aragtideenna','Our People':'Dadkeenna',
  'Headquartered in the heart of Mogadishu, 4CC INC. provides professional quality control, warehouse inspection and supply-chain services for local and international organizations operating across Somalia.':'Xarunteedu tahay bartamaha Muqdisho, 4CC INC. waxay adeegyo xirfadeed oo xakamaynta tayada, kormeerka bakhaarka iyo silsiladda sahayda siisaa hay’adaha maxalliga iyo kuwa caalamiga ah ee Soomaaliya ka hawlgala.','Our work is grounded in careful observation, transparent communication and an uncompromising commitment to the standards our clients expect.':'Shaqadeennu waxay ku dhisan tahay fiirsi taxaddar leh, xiriir hufan iyo u heellanaan aan gorgortan lahayn oo ku wajahan heerarka macaamiisheennu filayaan.','To safeguard quality and improve operational performance through accurate, independent and practical services.':'Inaan ilaalino tayada oo aan horumarino waxqabadka hawlgalka anagoo adeegsanayna adeegyo sax ah, madax-bannaan oo wax-ku-ool ah.','To become the region’s most trusted quality control and logistics partner.':'Inaan noqonno saaxiibka ugu kalsoonida badan gobolka ee xakamaynta tayada iyo saadka.','A capable local team that understands both global expectations and realities on the ground.':'Koox maxalli ah oo karti leh, fahamsanna filashooyinka caalamiga ah iyo xaqiiqada dhulka.',
  'Our expertise':'Khibraddeenna','Control, clarity and confidence—end to end.':'Xakameyn, hufnaan iyo kalsooni—bilow ilaa dhammaad.','Practical services designed to protect quality, reduce risk and keep your operation moving.':'Adeegyo wax-ku-ool ah oo loogu talagalay ilaalinta tayada, dhimista khatarta iyo socodsiinta hawlgalkaaga.','Structured field checks':'Kormeer goobeed nidaamsan','Photo-backed reporting':'Warbixin sawirro leh','Clear recommendations':'Talooyin cad','Responsive coordination':'Isku-duwid degdeg ah','Request this service':'Codso adeeggan',
  'Our work':'Shaqadeenna','Proof in every project.':'Caddeyn mashruuc kasta.','A look at how our teams bring control, visibility and dependable execution to complex operations.':'Eeg sida kooxaheennu u keenaan xakameyn, muuqaal iyo fulin lagu kalsoonaan karo hawlgallada adag.','Contact us':'Nala soo xiriir','Let’s move your operation forward.':'Aan horay u dhaqaajino hawlgalkaaga.','Tell us what you need. Our team will respond with practical next steps for your assignment.':'Noo sheeg waxa aad u baahan tahay. Kooxdayadu waxay kuugu jawaabi doontaa tallaabooyinka xiga ee wax-ku-oolka ah.','Get in touch':'Nala xiriir','Talk to our team.':'La hadal kooxdayada.','Visit us':'Nagu soo booqo','Call us':'Na soo wac','Email us':'Email noo soo dir','Working hours':'Saacadaha shaqada','Send an enquiry':'Soo dir codsi','Full name':'Magaca oo buuxa','Email address':'Cinwaanka email-ka','Phone number':'Lambarka telefoonka','Service':'Adeegga','Your message':'Fariintaada','Send message':'Dir fariinta','Message received':'Fariinta waa la helay','Send another message':'Dir fariin kale',
  'Company':'Shirkadda','Get in touch':'Nala xiriir','Admin portal':'Bogga maamulka','All rights reserved.':'Xuquuqda oo dhan way dhowran tahay.'
}

const LanguageContext=createContext(null)
export function LanguageProvider({children}){
  const [language,setLanguage]=useState(()=>localStorage.getItem('4cc_language')||(navigator.language.toLowerCase().startsWith('so')?'so':'en'))
  const reverse=useMemo(()=>Object.fromEntries(Object.entries(so).map(([en,value])=>[value,en])),[])
  useEffect(()=>{localStorage.setItem('4cc_language',language);document.documentElement.lang=language
    const translate=root=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const raw=node.nodeValue,trimmed=raw.trim(),table=language==='so'?so:reverse;if(table[trimmed])node.nodeValue=raw.replace(trimmed,table[trimmed])}for(const el of root.querySelectorAll?.('[placeholder]')||[]){const table=language==='so'?so:reverse;if(table[el.placeholder])el.placeholder=table[el.placeholder]}}
    translate(document.body);const observer=new MutationObserver(entries=>entries.forEach(entry=>entry.addedNodes.forEach(node=>{if(node.nodeType===1)translate(node)})));observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()
  },[language,reverse])
  return <LanguageContext.Provider value={{language,setLanguage}}>{children}</LanguageContext.Provider>
}
export const useLanguage=()=>useContext(LanguageContext)
